ClimaTempo/Controllers/CidadeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClimaTempo.DAL;
using ClimaTempo.Models;

namespace ClimaTempo.Controllers
{
    public class CidadeController : Controller
    {
        private context db = new context();

        // GET: Cidade
        public ActionResult Index()
        {
            return View(db.Cidade.ToList());
        }

        // GET: Cidade/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = db.Cidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // GET: Cidade/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Cidade/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,EstadoId")] Cidade cidade)
        {
            if (ModelState.IsValid)
            {
                db.Cidade.Add(cidade);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cidade);
        }

        // GET: Cidade/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = db.Cidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // POST: Cidade/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,EstadoId")] Cidade cidade)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cidade).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cidade);
        }

        // GET: Cidade/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cidade cidade = db.Cidade.Find(id);
            if (cidade == null)
            {
                return HttpNotFound();
            }
            return View(cidade);
        }

        // POST: Cidade/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cidade cidade = db.Cidade.Find(id);
            db.Cidade.Remove(cidade);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClimaTempo/Controllers/ClimaTempoController.cs
using ClimaTempo.DAL;
using ClimaTempo.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ClimaTempo.Controllers
{
    public class ClimaTempoController : Controller
    {
        // GET: ClimaTempo
        public ActionResult Index(string hoje)
        {
            if (String.IsNullOrEmpty(hoje))
            {
                hoje = DateTime.Now.ToString("yyyy-MM-dd");
            }

            context db = new context();
            ViewBag.Cidade = new SelectList(db.Cidade.Select(s => new { Text = s.Nome, Value = s.ID }).ToList(), "Value", "Text");
            ViewBag.Hoje = hoje;
            return View();
        }

        public ActionResult CardsPrevisaoSemana(string hoje, int idCidade = 0)
        {
            if (String.IsNullOrEmpty(hoje))
            {
                hoje = DateTime.Now.ToString("yyyy-MM-dd");
            }

            context db = new context();
            string[] hojeArray = hoje.Split('-');

            Int32.TryParse(hojeArray[0], out int ano);
            Int32.TryParse(hojeArray[1], out int mes);
            Int32.TryParse(hojeArray[2], out int dia);

            DateTime dataOrigem = new DateTime(ano, mes, dia);
            DateTime setimoDia = dataOrigem.AddDays(6);

            int cidade = idCidade == 0 ? 1 : idCidade;

            List<PrevisaoClima> previsaoSemana = db.PrevisaoClima
                .Where(w => w.DataPrevisao >= dataOrigem && w.DataPrevisao <= setimoDia && w.CidadeId == cidade)
                .OrderBy(o => o.DataPrevisao)
                .ToList();

            ViewBag.PrevisaoSemana = previsaoSemana;
            ViewBag.CidadeFiltrada = db.Cidade.Where(w => w.ID == cidade).Select(s => s.Nome).FirstOrDefault();

            return PartialView("_CardsPrevisaoSemana");
        }

        public ActionResult CardsCidadesMaisQuentesFrias(string hoje)
        {
            if (String.IsNullOrEmpty(hoje))
            {
                hoje = DateTime.Now.ToString("yyyy-MM-dd");
            }

            string[] hojeArray = hoje.Split('-');

            Int32.TryParse(hojeArray[0], out int ano);
            Int32.TryParse(hojeArray[1], out int mes);
            Int32.TryParse(hojeArray[2], out int dia);

            DateTime dataOrigem = new DateTime(ano, mes, dia);

            context db = new context();

            List<CidadesMaisQuentesFrias> cidadesMaisFrias = (from previsao in db.PrevisaoClima
                          join cidade in db.Cidade
                          on previsao.CidadeId equals cidade.ID
                          join estado in db.Estado
                          on cidade.EstadoId equals estado.ID
                          where previsao.DataPrevisao == dataOrigem
                          select new CidadesMaisQuentesFrias
                          {
                              Cidade = cidade.Nome,
                              Estado = estado.Nome,
                              TemperaturaMaxima = previsao.TemperaturaMaxima,
                              TemperaturaMinima = previsao.TemperaturaMinima
                          })
                          .OrderBy(o => o.TemperaturaMaxima).ThenBy(t => t.Cidade).ThenBy(t => t.Estado)
                          .Take(3).ToList();

            List<CidadesMaisQuentesFrias> cidadesMaisQuentes = (from previsao in db.PrevisaoClima
                                    join cidade in db.Cidade
                                    on previsao.CidadeId equals cidade.ID
                                    join estado in db.Estado
                                    on cidade.EstadoId equals estado.ID
                                    where previsao.DataPrevisao == dataOrigem
                                    select new CidadesMaisQuentesFrias
                                    {
                                        Cidade = cidade.Nome,
                                        Estado = estado.Nome,
                                        TemperaturaMaxima = previsao.TemperaturaMaxima,
                                        TemperaturaMinima = previsao.TemperaturaMinima
                                    })
                          .OrderByDescending(o => o.TemperaturaMaxima).ThenBy(t => t.Cidade).ThenBy(t => t.Estado)
                          .Take(3).ToList();

            ViewBag.CidadesMaisFrias = cidadesMaisFrias;
            ViewBag.CidadesMaisQuentes = cidadesMaisQuentes;
            ViewBag.Hoje = hoje;

            return PartialView("_CardsCidadesMaisQuentesFrias");
        }
    }
}

ClimaTempo/Controllers/EstadoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClimaTempo.DAL;
using ClimaTempo.Models;

namespace ClimaTempo.Controllers
{
    public class EstadoController : Controller
    {
        private context db = new context();

        // GET: Estado
        public ActionResult Index()
        {
            return View(db.Estado.ToList());
        }

        // GET: Estado/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estado estado = db.Estado.Find(id);
            if (estado == null)
            {
                return HttpNotFound();
            }
            return View(estado);
        }

        // GET: Estado/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Estado/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Nome,UF")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                db.Estado.Add(estado);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(estado);
        }

        // GET: Estado/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estado estado = db.Estado.Find(id);
            if (estado == null)
            {
                return HttpNotFound();
            }
            return View(estado);
        }

        // POST: Estado/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nome,UF")] Estado estado)
        {
            if (ModelState.IsValid)
            {
                db.Entry(estado).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(estado);
        }

        // GET: Estado/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Estado estado = db.Estado.Find(id);
            if (estado == null)
            {
                return HttpNotFound();
            }
            return View(estado);
        }

        // POST: Estado/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Estado estado = db.Estado.Find(id);
            db.Estado.Remove(estado);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClimaTempo/Controllers/PrevisaoClimaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ClimaTempo.DAL;
using ClimaTempo.Models;

namespace ClimaTempo.Controllers
{
    public class PrevisaoClimaController : Controller
    {
        private context db = new context();

        // GET: PrevisaoClima
        public ActionResult Index()
        {
            return View(db.PrevisaoClima.ToList());
        }

        // GET: PrevisaoClima/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrevisaoClima previsaoClima = db.PrevisaoClima.Find(id);
            if (previsaoClima == null)
            {
                return HttpNotFound();
            }
            return View(previsaoClima);
        }

        // GET: PrevisaoClima/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PrevisaoClima/Create
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,CidadeId,DataPrevisao,Clima,TemperaturaMinima,TemperaturaMaxima")] PrevisaoClima previsaoClima)
        {
            if (ModelState.IsValid)
            {
                db.PrevisaoClima.Add(previsaoClima);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(previsaoClima);
        }

        // GET: PrevisaoClima/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrevisaoClima previsaoClima = db.PrevisaoClima.Find(id);
            if (previsaoClima == null)
            {
                return HttpNotFound();
            }
            return View(previsaoClima);
        }

        // POST: PrevisaoClima/Edit/5
        // Para se proteger de mais ataques, habilite as propriedades específicas às quais você quer se associar. Para 
        // obter mais detalhes, veja https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,CidadeId,DataPrevisao,Clima,TemperaturaMinima,TemperaturaMaxima")] PrevisaoClima previsaoClima)
        {
            if (ModelState.IsValid)
            {
                db.Entry(previsaoClima).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(previsaoClima);
        }

        // GET: PrevisaoClima/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PrevisaoClima previsaoClima = db.PrevisaoClima.Find(id);
            if (previsaoClima == null)
            {
                return HttpNotFound();
            }
            return View(previsaoClima);
        }

        // POST: PrevisaoClima/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            PrevisaoClima previsaoClima = db.PrevisaoClima.Find(id);
            db.PrevisaoClima.Remove(previsaoClima);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ClimaTempo/Views/Shared/_CardsCidadesMaisQuentesFrias.cshtml
@{
    List<ClimaTempo.Models.CidadesMaisQuentesFrias> cidadesMaisQuentes = (List<ClimaTempo.Models.CidadesMaisQuentesFrias>)ViewBag.CidadesMaisQuentes;
    List<ClimaTempo.Models.CidadesMaisQuentesFrias> cidadesMaisFrias = (List<ClimaTempo.Models.CidadesMaisQuentesFrias>)ViewBag.CidadesMaisFrias;
}

<div class="col-12 row title-clima-tempo-hoje">
    <label>Clima Tempo para o dia : @ViewBag.Hoje</label>
</div>

<div class="col-12 row">

    <div class="col-lg-6">
        <label class="label-title-cidades">Cidades mais quentes hoje</label>
        <div class="panel panel-default panel-cidades">

            @{
                if (cidadesMaisFrias.Count == 0)
                {
                    for (int i = 0; i < 3; i++)
                    {
                        <div class="panel-body row-cidades">
                            <label class="pull-left">
                                <label class="label-nome-cidade">--</label> <br />
                                <label>--</label>
                            </label>

                            <label class="pull-right">
                                <label class="label-temp-max">Máx.: --</label> <br />
                                <label class="pull-right">Min.: --</label>
                            </label>
                        </div>
                    }

                }
                else
                {
                    foreach (var item in cidadesMaisQuentes)
                    {
                        <div class="panel-body row-cidades">
                            <label class="pull-left">
                                <label class="label-nome-cidade">@item.Cidade</label> <br />
                                <label>@item.Estado</label>
                            </label>

                            <label class="pull-right">
                                <label class="label-temp-max">Máx.: @item.TemperaturaMaxima °C</label> <br />
                                <label class="pull-right">Min.: @item.TemperaturaMinima °C</label>
                            </label>
                        </div>
                    }
                } 
            }
        </div>
    </div>

    <div class="col-lg-6">
        <label class="label-title-cidades">Cidades mais frias hoje</label>
        <div class="panel panel-default panel-cidades">
            @{
                if (cidadesMaisFrias.Count == 0)
                {
                    for (int i = 0; i < 3; i++)
                    {
                        <div class="panel-body row-cidades">
                            <label class="pull-left">
                                <label class="label-nome-cidade">--</label> <br />
                                <label>--</label>
                            </label>

                            <label class="pull-right">
                                <label class="label-temp-max">Máx.: --</label> <br />
                                <label class="pull-right">Min.: --</label>
                            </label>
                        </div>
                    }

                }
                else
                {
                    foreach (var item in cidadesMaisFrias)
                    {
                        <div class="panel-body row-cidades">
                            <label class="pull-left">
                                <label class="label-nome-cidade">@item.Cidade</label> <br />
                                <label>@item.Estado</label>
                            </label>

                            <label class="pull-right">
                                <label class="label-temp-max">Máx.: @item.TemperaturaMaxima °C</label> <br />
                                <label class="pull-right">Min.: @item.TemperaturaMinima °C</label>
                            </label>
                        </div>
                    }
                }
            }


        </div>
    </div>
</div>

ClimaTempo/Views/Shared/_CardsPrevisaoSemana.cshtml
@{
    List<ClimaTempo.Models.PrevisaoClima> previsaoSemana = (List<ClimaTempo.Models.PrevisaoClima>)ViewBag.PrevisaoSemana;
}

<div class="col-12 row title-clima-tempo-hoje">
    <label>Clima para os próximos 7 dias para a cidade de @ViewBag.CidadeFiltrada</label>
</div>

<div class="container">
    <div class="row">
        @{
            if (previsaoSemana.Count == 0)
            {
                for (int i = 0; i < 7; i++)
                {
                    <div class="col-lg-1 card-previsao-semana">
                        <div class="panel panel-default">
                            <div class="panel-heading panel-datas"><label>--</label> <br /> <label>--</label></div>
                            <div class="panel-body">
                                -- <br />
                                Mínima: -- <br />
                                Máxima: --
                            </div>
                        </div>
                    </div>
                }

            }
            else
            {
                foreach (var item in previsaoSemana)
                {
                    var culture = new System.Globalization.CultureInfo("pt-BR");
                    var day = culture.DateTimeFormat.GetDayName(item.DataPrevisao.DayOfWeek);

                    <div class="col-lg-1 card-previsao-semana">
                        <div class="panel panel-default">
                            <div class="panel-heading panel-datas"><label>@item.DataPrevisao.ToString("dd/MM/yyyy")</label> <br /> <label>@day</label></div>
                            <div class="panel-body">
                                @item.Clima <br />
                                Mínima: @item.TemperaturaMinima °C <br />
                                Máxima: @item.TemperaturaMaxima °C
                            </div>
                        </div>
                    </div>
                }
            }
        }
    </div>
</div>

ClimaTempo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Clima Tempo", "Index", "ClimaTempo", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Previsão Climas", "Index", "PrevisaoClima")</li>
                    <li>@Html.ActionLink("Cidades", "Index", "Cidade")</li>
                    <li>@Html.ActionLink("Estados", "Index", "Estado")</li>
                    <li>@Html.ActionLink("Clima Tempo", "Index", "ClimaTempo")</li>*@

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
    </div>
    
    @RenderSection("scripts", required: false)
</body>
</html>